### PR TITLE
Group Facebook together

### PR DESCRIPTION
**Pull request by raunsbaekdk**
Hi

I added Facebook as a group option.

### CODE REVIEW

**Comment by raunsbaekdk** [comment]
Hi @dannyvankooten 

Is there anymore to add, before this PR can be merged?

**Comment by dannyvankooten** [comment]
Hey @raunsbaekdk,

Sorry, I've been mostly offline for the last 2 weeks but will be reviewing this PR soon. I'm definitely keen on grouping Facebook, the only thing holding me back to merging this right away is the lack of a proper grouping mechanism (in code) as the current method may prove unwieldly very soon...

**Comment by raunsbaekdk** [comment]
Hi @dannyvankooten 

Great to hear from you. Are there a big upgrade in the making?

Should I close the PR for now?

**Comment by jjjjeeffff** [comment]
This could incorrectly group URLs like `facebook.<companyname>.com`, right? May be safer to extract apex domain and compare on that.

**Pull request closed without merging**
