### PR TITLE
Update Heroku.md

### PR DESCRIPTION
**Pull request by gmolveau**
add a complete guide on how to deploy fathom on heroku via the heroku-cli.

### CODE REVIEW

**Comment by sgasser** [comment]
Is it possible to add the Heroku button? https://devcenter.heroku.com/articles/heroku-button

**Comment by gmolveau** [comment]
@sgasser I don't think so but I will check.

**Comment by sgasser** [comment]
Why not? It's the easiest way...

**Comment by gmolveau** [comment]
Because we're pushing the binary and not the all-project, we need a custom buildpack and some preliminary operations so I don't know if it's possible.

**Comment by JackEllis** [comment]
Although I likely wouldn't deploy Fathom on DO due to costs, some people might! Thanks so much for writing up some instructions @gmolveau !

**Pull request merged**
