### PR TITLE
Update Makefile and Dockerfile for non-amd64 support

### PR DESCRIPTION
**Pull request by mcrosson**
Allow building Fathom for non-amd64 architectures by adding variables to the Dockerfile as well as Makefile.

The Makefile has been updated to have "ARCH" as a build variable that defaults to amd64 (current arch).

The Dockerfile has been updated for more granular control over the go build arch as well as which images are used for asset builds, go builds and final image creation.

Dockerfile was also updated to include pgsql/mysql/sqlite clients inside the final container to help end-users troubleshoot any database connection issues that may arise.

Example build invocation for arm64v8 architecture (tested working):
```
docker build \
    --file ./Dockerfile \
    --build-arg ASSETDIST=arm64v8/node:alpine \
    --build-arg GODIST=arm64v8/golang:alpine \
    --build-arg RELEASEDIST=arm64v8/alpine:latest \
    --build-arg GOARCH=${GOARCH} \
    --tag arm64v8/fathom:latest \
    .
```

### CODE REVIEW

**Comment by dannyvankooten** [comment]
Hey @mcrosson,

Thank you for this PR! 

However, my Docker knowledge is quite limiting and I'm not 100% sure whether we should include MySQL **and** Postgres **and** SQLite in the final container? 

- Should we make this choice? 
- Shouldn't the database live in a separate Docker container?

What are your thoughts on this?

If you could submit the Makefile changes in a separate PR then I'll merge those right away. No doubts about these!

**Comment by mcrosson** [comment]
@dannyvankooten The Dockerfile only includes the different database clients for supported database back ends. I did not change the intent of running the database in a different container.

This was just a 'nice to have' that allows for troubleshooting sqlite/mysql/postgresql from within the container if necessary.

```docker exec -it fathom /bin/sh``` for example will let you run a shell within the container and then run the sqlite/mysql/psql clients from within the container if having troubles.

I can remove the clients from the container if you feel that appropriate.

**Comment by dannyvankooten** [comment]
Hey @mcrosson,

Sorry, a tad late as I was busy but after giving this some more thought I definitely think that we should not be including those 3 databases in the same container as Fathom is in. People should either spin-up a separate container for their database, use a Docker volume or use a cloud provider. 

The reason is mostly that people are running this Docker container in production, so they probably don't want 2 unused databases drivers in their container taking up resources.

**Comment by mcrosson** [comment]
@dannyvankooten Did the updates for arm64 support (https://github.com/usefathom/fathom/pull/81/commits/8899edaad8b32d784eabf57f88827319957bd658) make it into the latest commits?

I'm not seeing any Dockerfile or Makefile updates that would allow a vanilla build on arm[64]

**Comment by dannyvankooten** [comment]
Hi @mcrosson. Yes, but only as prebuilt binaries through GitHub’s releases tab (built and uploaded with the use of GoReleaser). No additional Docker container.

**Comment by mcrosson** [comment]
@dannyvankooten Would it be possible to incorporate the changes I linked? I would prefer to build off the official sources/Dockerfile rather than roll my own based on the released binaries.

I'm working on a project that is mirroring builds (to help ease strain on upstreams and to help with arm containers) and we'd much prefer to work with upstreams to provide build options than "go it alone" for containerized builds.

Note: I'm not asking you to release pre-built arm images ;)

**Comment by dannyvankooten** [comment]
Hi @mcrosson, which changes specifically? Because we're really not looking to include database engines in the containers themselves. 

But also: wouldn't it be fairly trivial to maintain your own Docker build that pulls in the Fathom repository? That way, you can make it do exactly what you want it to while you're not dependent on us in any way. And we get to focus on improving Fathom itself. :)

**Comment by mcrosson** [comment]
@dannyvankooten It would be "trivial" but I don't like deviating much, if at all from upstream.

Mainly the build parms to pass the go arch through. The existing Makefile is setup for just amd64 as the arch and if nothing else that'd be a good update for my project.

And I can appreciate wanting to focus on just the Fathom bit ;) I'm just hoping we can find a solid middle ground so my project can build directly from sources, if possible. If not, we can use curl + jq to find the latest release...

**Pull request closed without merging**
