### PR TITLE
Add 1-click "Deploy to Heroku" button

### PR DESCRIPTION
**Pull request by JaneJeon**
Hi!

I know that [this tutorial](https://gist.github.com/gmolveau/78f88af3f5951ba6e093f93a07caa302) exists and it was sort of the "official" close of #59, but a lot of the work is duplicitous and I added some files to allow Fathom to run on Heroku via Docker.

I've already tested it out on my own Heroku account, and it works (it's super easy too)!

As for the Dockerfile "magic", the only bit I had to change was remapping the database port (which is why the end of the `Dockerfile.heroku` looks _slightly_ different, but other than that they're the same).

I hope this gets merged. Thanks!

### CODE REVIEW

**Comment by JaneJeon** [comment]
Also this would negate any need for Heroku-specific docs, so that's one less thing to maintain

**Comment by JaneJeon** [comment]
Uhh.... what happened to my branch? it had the button and everything

**Comment by JaneJeon** [comment]
Like, you can clearly see that you overwrote https://github.com/usefathom/fathom/tree/fdcecc57c40f71c0a04b47f96abdc724df8a5b1e by force pushing...

**Comment by JackEllis** [comment]
@JaneJeon This was me, I edited the reader file in GitHub to reflect some changes. No intentions to close your PR, sorry.

**Comment by JaneJeon** [comment]
Oh man, it's gonna be a pain to recover it...

**Pull request closed without merging**
