### PR TITLE
Prevent tracking pageview from localhost

### LINKED ISSUE #287: Ignore requests from localhost
I'm hosting fathom myself on a docker container and I see in the dashboard that it's captured some requests from localhost. (Probably my own activity during development)

Is there a way to blacklist localhost or any other specific host? I did go over some of the other issues and commits that seem to address this, but they don't seem to have applied in my case, or no longer work.

### PR DESCRIPTION
**Pull request by EnKrypt**
This fixes #287

### CODE REVIEW

**Comment by EnKrypt** [comment]
@JackEllis Pinging cause it's been a while. Let me know if you've had the time to take a look at this.

**Comment by EnKrypt** [comment]
@JackEllis any kind of update would be cool. It's been a month and a half.

Just FYI, this patch is only 3 lines of code, so shouldn't take more than a minute to review if you decide to.

**Comment by fjeddy** [comment]
This should be optional, not forced... This code would require you to push to a live / dev site before you can test if Fathom is working correctly.

**Comment by JackEllis** [comment]
@fjeddy I agree 100%. Our advice on how to ignore tracking from localhost is here: https://usefathom.com/support/localhost

**Comment by EnKrypt** [comment]
This is bad advice. Yes, it should be optional of course, but it should be the other way around.

I'd wager that most people don't want to track localhost and in the case where you have to test fathom before deploying, that phase lasts for a short while before it is eventually deployed to production for its remaining lifespan where this feature is not required.

Ignoring localhost thus **should be the default**, with tracking localhost being an option you can go out of your way to enable.

At least, this is my opinion. It seems to be a feature that quite a few people want.

**Pull request closed without merging**
