### PR TITLE
add heroku 1-click support

### PR DESCRIPTION
**Pull request by JaneJeon**
I managed to recover #290. Basically you can remove `docs/misc/Heroku.md` (if you'd like) and close #279 since this button handles everything for you - no need for the complicated process!

As stated in #290, I've already had this up and running on my own Heroku account serving my own sites for some time now, so I know it works.

Here's to hoping this doesn't get `git push -f`'d this time 😅 @JackEllis

### CODE REVIEW

**Comment by JackEllis** [comment]
@JaneJeon Liking the looks of it. We'll likely merge this in but remove the big button on the repo readme file. Thanks for recovering it!

**Comment by JaneJeon** [comment]
@JackEllis hi thanks for replying

The "big button" is what allows people to literally deploy to Heroku with 1 click, so maybe if you don't want it on the top, you can move it down the README? Either way, Heroku buttons do need to be on the README of the repo...

**Comment by JaneJeon** [comment]
Aha, I downsized the heroku button so now it fits in with the rest of the badges. I think this fits your criteria?

**Comment by JackEllis** [comment]
@JaneJeon That's more along the lines of what we're after, thank you!

**Comment by JaneJeon** [comment]
Also please feel free to update the docs on deploying to heroku - 'cause now all you need to do is say "hey look at the `deploy to heroku` button on the README. Just click it"

**Comment by JaneJeon** [comment]
@JackEllis any updates on the merge?

**Comment by JaneJeon** [comment]
@JackEllis you overwrote my changes _again_ with your README force push... can you just merge this?

**Pull request closed without merging**
